"""Default HTML interface labels. Unknown locales fall back to English."""

ZH_TW = {'Skip to content': '跳至內容',
 'Code documentation': '程式碼文件',
 'Main': '主要導覽',
 'Overview': '總覽',
 'Source index': '原始碼索引',
 'Browse documentation': '瀏覽文件',
 'Find a page': '尋找頁面',
 'Find a page…': '尋找頁面…',
 'Expand all': '全部展開',
 'Collapse all': '全部收合',
 'Project documents': '專案文件',
 'No matching pages.': '找不到符合的頁面。',
 'Choose a guide to get started.': '選擇一份指南開始閱讀。',
 'Follow links for more detail.': '透過連結瞭解更多細節。',
 'On this page': '本頁目錄',
 'Documents': '文件',
 'Anchors': '錨點',
 'Files linked': '已連結檔案',
 'Unbound concepts': '未綁定概念',
 'Start here': '從這裡開始',
 'Documentation review': '文件審查',
 'All documents match their reviewed versions.': '所有文件皆與已審查的版本一致。',
 'Build report': '建置報告',
 'No problems found.': '未發現問題。',
 'Source file index': '原始碼檔案索引',
 'Role': '角色',
 'Anchor': '錨點',
 'Symbol': '符號',
 'Lines': '行號',
 'No wiki coverage.': '尚無 Wiki 文件涵蓋。',
 'Explore next': '接著探索',
 'Source references': '原始碼參照',
 'Page source': '頁面來源',
 'Breadcrumb': '階層導覽',
 'Reading path': '閱讀路徑',
 '01 Architecture': '01 架構',
 '02 Component': '02 元件',
 '03 Implementation': '03 實作',
 'Depends on': '相依於',
 'Used by': '使用者',
 'Page sections': '頁面章節',
 'Diagram destinations': '圖表連結目的地',
 'Components': '元件',
 'Implementation': '實作',
 'Open in editor ↗': '在編輯器開啟 ↗',
 'Decisions and change references': '決策與變更參照',
 'Continue exploring': '繼續探索',
 'Owned file': '負責說明的檔案',
 'Anchors here': '此處的錨點',
 'Read-only references': '唯讀參照',
 'Declarations referenced by this document.': '此文件參照的宣告。',
 'open': '開啟',
 'Follow a linked node to explore its component or implementation.': '點選已連結的節點，探索其元件或實作。',
 'Language': '語言',
 'English fallback: this page has not been translated yet.': '此頁尚未翻譯，暫時顯示英文內容。',
 'Architecture': '架構',
 'Component': '元件',
 'Subsystem': '子系統',
 'Manual': '使用手冊',
 'stable': '穩定',
 'draft': '草稿',
 'current': '已審查且無變更',
 'outdated': '審查後已有變更',
 'unreviewed': '尚未審查',
 'Related:': '相關文件：',
 'Owned by': '負責說明的文件：',
 'Referenced as read-only by:': '由下列文件唯讀參照：',
 'What you need to know before touching a file. This is the view an LLM should be handed when it is about to edit code.': '修改檔案前應瞭解的資訊。LLM '
                                                                                                                          '準備編輯程式碼時，應先閱讀這個檢視。',
 'Toggle pages under': '切換下列頁面的子頁：',
 'documentation': '文件',
 'Built': '建置日期',
 'anchors': '錨點',
 'files': '檔案',
 'pending of': '份待審查，共',
 'documents. Outdated means changed since review, not necessarily incorrect.': '份文件。審查後已有變更，不代表內容一定錯誤。',
 'guide': '指南',
 'This status reflects the latest site build.': '此狀態反映最近一次網站建置的結果。',
 'Last review:': '上次審查：',
 'Source changed:': '原始碼已變更：',
 'build notes to review': '則建置提示待檢查',
 'Link to': '連到',
 'owned files': '個負責說明的檔案',
 'stable anchors': '個穩定錨點',
 'linked declarations': '個連結宣告',
 'references': '個參照',
 'Architecture you can read, then inspect': '先閱讀架構，再檢視實作',
 'Changed since last review': '自上次審查後已有變更',
 'No review baseline': '尚無審查基準'}

def translate(text, locale, count=None):
    if locale == "ch_tw":
        return ZH_TW.get(text, text)
    if count == 1:
        return {"owned files": "owned file", "stable anchors": "stable anchor",
                "linked declarations": "linked declaration",
                "build notes to review": "build note to review"}.get(text, text)
    return text
